### ISSUE TITLE
Error: Cloud not start Firestore Emulator, port taken.

### ISSUE THREAD

**Issue by 0514kento** [ycu-engine/ds-club-site#101]
### 質問の内容

yarn dev をした際にエラーが出てしまい、localhostが開くことができません。
対処方法が不明です。

### スクリーンショットや該当のコード

<img width="1440" alt="Screen Shot 2022-09-03 at 19 08 29" src="https://user-images.githubusercontent.com/108796544/188265947-48c203ec-fbe8-49d6-8d19-71ff9aea7442.png">

**Comment by YutaUra** [comment]
vscode のコマンドパレット（`⌘ ⇧ P`）で `reload window` というコマンドを実行してみてください。

**Comment by 0514kento** [comment]
解決しました。
ありがとうございます🙏
