### ISSUE TITLE
GraphQL playgroundが立ち上がらない

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#126]
### 質問の内容

queryのテストをしようと思い、GraphQL Playground上で操作しようと思ったのですが、見つかりません。

`services/backend/src/index.ts`

```
import { createServer } from './server'

const bootstrap = async () => {
  const server = await createServer()

  const { url } = await server.listen()
  console.info(`🚀 Server ready at ${url}`)
}

void bootstrap()

```

`workspace`で`yarn dev`しても`🚀 Server ready at ...`が表示されないです

### スクリーンショットや該当のコード

<img width="811" alt="image" src="https://user-images.githubusercontent.com/104000239/191466215-e78f43a1-ef08-4149-a0ee-13992e25cb7c.png">

### 解決方法

moduleが抜けてるので`yarn`すればOK

**Comment by YutaUra** [comment]
これっぽいな

<img width="592" alt="スクリーンショット 2022-09-22 12 44 42" src="https://user-images.githubusercontent.com/45471709/191653741-a5e99b0b-5df8-4b36-b95c-7be6a1f13328.png">

`yarn` してみたら治るかも？

**Comment by nyatinte** [comment]
@YutaUra 
`yarn`したら治りました！うっかりしてました。ありがとうございます！
