### ISSUE TITLE
もりけん にオリエンする

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#13]
### 完了条件

- [x] git の使い方を教える
  - git を使った開発ができるようになる（`clone`, `pull`, `switch(branch)`, `add`, `commit`, `push`)
- [x] ページの作り方を教える
  - 開発サーバーの起動の仕方
  - どこにページを作成すればいいか
  - ページ作成のお作法を教える

### 参考資料

- https://github.com/ycu-engine/community/wiki/Github-and-git-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB

**Comment by YutaUra** [comment]
明後日（2022/07/29）のもくもく会のタイミングでオリエンを行いたい。

@Kakeru-Sato @mokroke @nyatinte 誰かにお願いしたいんですが、やりたい or やってもいいよって人いますか？？

**Comment by Kakeru-Sato** [comment]
確認遅くなって申し訳ないです。
僕の方で対応進めていきます。

**Comment by YutaUra** [comment]
完了済みです
