### ISSUE TITLE
教材ページのフロント作成

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#159]
### 教材について

- 教材は Google Drive の特定のフォルダーに保存されているものをAPIで取得して使うようにする
- 教材の種類は現状以下を想定しているため、これに対応する形でフロントを作る必要がある。
  - Google Slides
  - Python Notebook
  - PDF（将来的に対応見込みですが、今回は一旦スキップします）
- Google Slides に関しては 埋め込み用のURLをAPIから返すので、それを表示させればOKです
- Python Notebook に関しては [react-jupyter-notebook-viewer](https://www.npmjs.com/package/react-jupyter-notebook-viewer) を使ってください。ライブラリに必要なデータはAPIから返すことにします

### 参考情報

- Figma: https://www.figma.com/file/MWkK3HSnbCPNLR1ADe3mw9/Engine-%E3%82%AF%E3%83%A9%E3%83%96%E7%94%A8%E3%82%B5%E3%82%A4%E3%83%88?node-id=3%3A33
- Google Slides 埋め込み: https://piecedesign.net/2020/04/19/google%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E3%82%92%E3%83%9B%E3%83%BC%E3%83%A0%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AB%E5%9F%8B%E3%82%81%E8%BE%BC%E3%82%80
- [react-jupyter-notebook-viewer](https://www.npmjs.com/package/react-jupyter-notebook-viewer)

**Comment by nyatinte** [comment]
把握しました！

**Comment by YutaUra** [comment]
closed by #162
