### ISSUE TITLE
yarn dev をすると `Can't resolve '@apollo/clinent'` のErrorが出る

### ISSUE THREAD

**Issue by takusan2** [ycu-engine/ds-club-site#21]
yarn dev を実行し、localhost3000に行くと以下のようなエラーが発生する。
[<img width="964" alt="Screen Shot 2022-08-01 at 22 49 19" src="https://user-images.githubusercontent.com/106806920/182191583-ba4f9ec4-a544-4f4f-bda7-c173672d7a2f.png">
](url)

手作業で追加・変更したファイルは
`experimentForm`
`InputBox`
`InputPasswordBox`
だけなので、このエラーには関係ないと思います。

私が、mergeした時にgithubのcheckというのが動いたので、そこで何かが書き変わってしまったのでしょうか。
解決方法を教えてください。

いろいろ見てみたところ、firebaseとapollo があるところ`parsing error`が出ている

**Comment by YutaUra** [comment]
一回手元で `yarn` って実行して、追加ライブラリのインストールを試してみてください！

**Comment by takuya-okada-01** [comment]
`yarn` を実行したら解決しました！ありがとうございます！
また同じことを起こしてしまはないように聞いておきたいのですが、どうしてこうなってしまったのか教えていただけると嬉しいです。自分が余計な操作をしてしまったのかどうかも知りたいので。時間ある時お願いします！

**Comment by takusan2** [comment]
`yarn` を実行したら`yarn dev`で問題なく`localhost3000`が立ち上がり、ページが見れるようになりました！しかし、ほとんどのファイルで、`import`のところで同じようなエラー出ています。とりあえず、僕のページに出ているものを載せます
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/pages/doneExperimentForm.tsx.
The file must be included in at least one of the projects provided.
```

**Comment by YutaUra** [comment]
👍 そうしたら、一旦この問題は解決ですね！
eslint のエラーは現在の `main` ブランチでは修正されていると思うので、`main` ブランチを最新にした後に、`main` ブランチを作業ブランチへマージしてみてください！（やり方が不安な場合は一緒にやりましょう）

**Comment by takusan2** [comment]
eslintエラーは別の問題だったんですね！ありがとうございます！
わかりました。やってみます！ありがとうございます😭
