### ISSUE TITLE
memory.tsxをstudy_log.tsxに変える

### ISSUE THREAD

**Issue by mokroke** [ycu-engine/ds-club-site#36]

**Comment by YutaUra** [comment]
ファイル名を変更するだけの簡単なお仕事

**Comment by takusan2** [comment]
memory.tsx を studyRecord.tsx に変更しました。

**Comment by YutaUra** [comment]
@takuya-okada-01 
あれ！ `study_log.tsx` ではなく、 `studyRecord.tsx` にした理由ってなんでしょうか？？！

また、 URL には `cameCase` ではなく、 `snake_case` が適しているので、せめて `study_record.tsx` にしていただきたいです！

**Comment by takusan2** [comment]
study_log.tsx にします！snake_caseの方が適しているんですね、了解しました！

**Comment by YutaUra** [comment]
よろしくお願いします 🙇
