### ISSUE TITLE
改行しないようにするためにはどうすればいいでしょうか。

### ISSUE THREAD

**Issue by 0514kento** [ycu-engine/ds-club-site#51]
<img width="1440" alt="Screen Shot 2022-08-10 at 19 10 23" src="https://user-images.githubusercontent.com/108796544/183876199-d37a870e-49cc-4561-b18a-5a5c7b4aaf9a.png">

名前：浦優太　としたいのですが、解決法がわかりません。どなたか手を貸してください！！

**Comment by YutaUra** [comment]
実際のコードも貼り付けてください！貼り付ける際は、コメントではなく、トップの文章を編集し、画像の下になるようにしてください！

その際は以下のようにバッククオーティションで囲ってください！

````
```tsx
const Page = () => {
  return (
    <div>
      ...
    </div>
  )
}
```
````

**Comment by nyatinte** [comment]
@0514kento 
cssの`white-space: nowrap`を使ってみてはどうでしょうか？

```tsx
<Text whiteSpace='nowrap'>
  名前: ****
</Text>
```
みたいな感じです

**Comment by 0514kento** [comment]
```
 <Text color="pink.500" fontSize="3xl" textAlign="center">
              名前：<Text color="#000">浦優太</Text>
```

この部分に編集が必要かとおもいます

**Comment by 0514kento** [comment]
拓実くんありがとう

**Comment by YutaUra** [comment]
@nyatinte が言及してくれている内容でも解決する可能性がありますが、補足します！

前提として、 chakra-ui の Text 要素はデフォルトでは `<p>` タグを出力します。

`<p>` タグは段落を表すタグで、一つの文章になることを意味します。

つまり、

```tsx
<Text color="pink.500" fontSize="3xl" textAlign="center">
  名前：<Text color="#000">浦優太</Text>
</Text>
```

は、

```html
<p>
  名前：<p>浦優太</p>
</p>
```

と同じ出力になります。

`<p>`タグの中に`<p>`タグを入れることは可能ではありますが、今回のケースでは「文章の中に文章がある」という意味的構造は的確ではありません。

そこで、使うべきタグは文の断片を意味する `<span>` タグです。

chakra-ui では `<Text as="span" />` のように `as` props にタグ名を指定することで出力されるタグを変えることができます。

```tsx
<Text color="pink.500" fontSize="3xl" textAlign="center">
  名前：<Text as="span" color="#000">浦優太</Text>
</Text>
```
↓
```html
<p>
  名前：<span>浦優太</span>
</p>
```

そして、このように変えることで、元々の問題である 「文字が改行されてしまう」 問題も合わせて解決します。

理由は `p` タグは標準でブロック要素であるのに対し、 `span` タグは標準でインライン要素だからです。

ブロック要素は簡単にいうと、要素ごとがどんどん縦に並んでいくといったものに対し、インライン要素はブロック要素の中の隙間に入り込むような配置がされます。

これらについて少しだけ調べてみると、より理解が深まると思います。

蛇足になりますが、質問をする際は、スクショと実際のコードを載せていただけると回答がよりしやすくなります。

**Comment by 0514kento** [comment]
浦さんありがとうございます！
めちゃめちゃわかりやすい説明でした。
スクショとコーディングを貼り付ける方法もわかりました！！

**Comment by YutaUra** [comment]
もし、問題が解決した場合は issue を close しちゃってください 👍
