### ISSUE TITLE
逆に改行はどうやるのかが知りたいです！

### ISSUE THREAD

**Issue by 0514kento** [ycu-engine/ds-club-site#56]
<img width="1440" alt="Screen Shot 2022-08-12 at 1 15 16" src="https://user-images.githubusercontent.com/108796544/184180532-0643fcc3-77f0-4a86-adc5-e002f3c7e20b.png">

1. , 2. , ... ごとに改行、また、"会費についての注意事項"のところから段落をつけて箇条書きにしたいです。
明日の勉強会は出れません。よろしくお願い致します。

```
<Box background="#fff" borderRadius="3xl" flex={1} p={5}>
            <Text fontSize="2xl" textAlign="left">
              &emsp;会費についての注意事項
            </Text>

            <Text fontSize="2xl" textAlign="center">
              1.会費の徴収は4月と10月に行います 2.徴収金額は3000円です
              3.脱退される場合、月割り計算で差額を返金致します
              4.会費を期限内に納めていただけない場合、除名処分及び在籍期間中の会費を請求します
            </Text>
          </Box>
```

↓作りたいもの
会費についての注意事項
　
　1.~

   2.~

**Comment by 0514kento** [comment]
一番下の作りたいものの　2.~の前にもスペース入れたいです

**Comment by takusan2** [comment]
箇条書き用の要素があるのでそれを使うとこんな感じで書けます。

- 丸の箇条書き
```javascript
<ul>
    <li>会費の撤収〜</li>
    <li>脱退される場合〜</li>
    <li>会費を期限内〜</li>
</ul>
```
![Screen Shot 2022-08-12 at 9 12 11](https://user-images.githubusercontent.com/106806920/184262645-2e981bf2-5966-4a23-8213-d092c6a01011.png)


- 数字付きの箇条書き

```javascript
<ol>
    <li>会費の撤収〜</li>
    <li>脱退される場合〜</li>
    <li>会費を期限内〜</li>
</ol>
```
![Screen Shot 2022-08-12 at 9 13 15](https://user-images.githubusercontent.com/106806920/184262742-da1dd138-2537-4310-9320-7a5cd6bbad62.png)



`<ol>`はordered list 、`<ul>`はunordered listが由来のみたいです

**Comment by YutaUra** [comment]
Chakra-ui の `OrderedList` と `ListItem` を使うのが良さそうに感じます！

https://chakra-ui.com/docs/components/list

```tsx
<OrderedList>
  <ListItem>Lorem ipsum dolor sit amet</ListItem>
  <ListItem>Consectetur adipiscing elit</ListItem>
  <ListItem>Integer molestie lorem at massa</ListItem>
  <ListItem>Facilisis in pretium nisl aliquet</ListItem>
</OrderedList>
```
