### ISSUE TITLE
ログインしている人だけがみれるようにするコンポーネントを適用していく

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#62]
### 完了条件

- [ ] ログインが必要なページ全てが、ログインしないとみれない状態になるようにする
  - 具体的には以下のページ以外について適用すること
    - 体験入会申請ページ（確認ページ・完了ページ）
    - 会員規約ページ

### 参考資料

すでにトップページはログインが必要なようになっている。

この PR の内容を確認すること
https://github.com/ycu-engine/ds-club-site/pull/43

**Comment by takusan2** [comment]
#81 Authenticated の適用
