### ISSUE TITLE
権限管理ページ のワイヤーフレームを作成する

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#66]
### 前提条件

- #63 

### 完了条件

- [ ] Figma でワイヤーフレームを作成する

**Comment by YutaUra** [comment]
@mokroke サポートしてあげてください！

**Comment by takusan2** [comment]
@mokroke 
権限管理ページはどんな機能を考えればいいですか？
- 権限を変更できる
- ?

名前とその人の権限が見えて、変更できるような感じですかね？

**Comment by mokroke** [comment]
@takuya-okada-01 
イメージとしては、運営用ページ1みたいな形で、クリックすると権限を変更できるような形にしてほしい！

**Comment by takusan2** [comment]
@mokroke 
一旦作ってみたんですけど、どうですか？
もしよかったら、コメントかissueをクローズしてください🙇

![Image](https://user-images.githubusercontent.com/106806920/188311035-1d30f041-660b-443c-ae7f-7672e1473d6c.png)

**Comment by mokroke** [comment]
@takuya-okada-01 
連絡遅れて申し訳ないです！
notionの機能みたいでいい感じですね！
ありがとう！
