### ISSUE TITLE
体験入会の管理ページのワイヤーフレームを作成する

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#68]
### 完了条件

- [ ] ワイヤーフレームを作成する
  - ページに必要な機能は？
    - 入会申請を確認することができる
      - いつ申請したか確認できる
      - いつまで体験入会か確認できる
    - 体験入会のキャンセル機能がある

**Comment by takusan2** [comment]
いまさらで申し訳ないです。
このページは管理者権限を持っている人がみるページですか？それとも、体験入会をしている人が見る画面ですか？

**Comment by YutaUra** [comment]
管理者ページです！

**Comment by takusan2** [comment]
了解しました！ありがとうございます！！

**Comment by takusan2** [comment]
# 体験入会管理ページのワイヤーフレームの作成
体験入会者の「名前」「体験開始日」「体験終了日」「キャンセル」の項目を表にしました。
キャンセルはボタンとし、確認画面を一度出してから「はい」などのボタンを押して
キャンセル処理を実行という形がいいのかなと感じました。

# 疑問
体験入会者の情報をどのように取得する方針なのかが知りたいです。
おそらく体験入会申請フォームを送信したときにデータベースに登録した内容を
使うと思うのですが、万が一のために手入力ができる機能も必要でしょうか？

<img width="793" alt="Screen Shot 2022-08-18 at 19 13 49" src="https://user-images.githubusercontent.com/106806920/185371407-8d20e28a-c4da-4ff3-b77a-d11d3c7d87d3.png">

**Comment by nyatinte** [comment]
@mokroke 
もしOKならcloseお願いします！

**Comment by mokroke** [comment]
@nyatinte @takuya-okada-01 
連絡遅れて申し訳ないです！
キャンセルボタンに関しては確認画面を出す形で大丈夫です！
ワイヤーフレームに関してはOKです！
