### ISSUE TITLE
画像のアップロードがうまく行えない

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#7]
# 概要
`react-hook-form`を用いた画像のアップロードが行えない

# 再現手順

1. 画像を追加
2. 必須事項のformを埋める
3. 追加するボタンを押す
4. コンソールを開き、出力をみる
5. 画像の詳細なデータがうまく記載されていない

# 修正しないとどう困るか
問題を作成するときに画像が追加できない

# 原因
`react-hook-form`を用いて管理した？

# 修正案

- 画像追加部分のみは`react-hook-form`を使用しない
- データベースに管理し、画像を追加するときはURLを指定する

**Comment by takusan2** [comment]
```javascript
154-  <form onSubmit={() => handleSubmit(onSubmit)}>
154+  <form onSubmit={handleSubmit(onSubmit)}>
```
と書き換えるとconsole画面にデータが表示された（下の画像の通り）
俺が前にアロー関数にすると挙動が変わるっていったやつだと思う。エラーも出てないから問題ないと思うけど、なんでか詳しくはわかんないごめん。参考にしてみて！

<img width="487" alt="Screen Shot 2022-08-06 at 22 02 05" src="https://user-images.githubusercontent.com/106806920/183249994-88547b23-25d2-4902-9e05-f499cf0f3f05.png">

**Comment by YutaUra** [comment]
react-hook-form を使って画像の管理することできますよ！
ちょっとどこのコードかわからないので、もう少し詳細を追加してください！
