### ISSUE TITLE
メンティー一覧ページのワイヤーフレームを作成する

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#70]
### 完了条件

- [ ] Figma に メンティー一覧ページを作成する
  - ページに必要な機能など
    - メンティーの情報（メンティーのマイページを見れるような導線を用意する）
    - （もしかしたら）メンターからメンティーへのフィードバックを記録する（一旦デザインには用意しない）

**Comment by nyatinte** [comment]
@mokroke 
もしOKだったらissueをcloseしちゃってください！

**Comment by mokroke** [comment]
@YutaUra 返信遅れて申し訳ないです！
大丈夫です！ありがとうございます！
