### ISSUE TITLE
メンター・メンティー管理ページのワイヤーフレームを作成する

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ds-club-site#74]
### 完了条件

- [ ] Figma で メンター・メンティー管理ページのワイヤーフレームを作成する
  - このページに必要な機能・情報など
    - メンターを追加できる
    - メンティーを設定できる(属性がまだついてない人だけ)
    - チームを削除・追加できる
    - チームを選択できる

**Comment by nyatinte** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/104000239/184663921-7c31b9f1-3608-42f1-a341-d240ac7caad9.png">
こんな感じで作成してみました

@mokroke 
ちょっと要件の部分が曖昧だったんですけど、こんな感じで大丈夫ですかね？
修正点とかあれば教えて欲しいです。
