### ISSUE TITLE
バックエンド関連で用いられているライブラリを知りたい

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#76]
### 質問の内容

個人で1から環境構築ができるようになりたいので、バックエンド関連の環境を知りたいです。

現段階ではこのように認識しています

- TypeScript
- GraphQL
  - codegen
- Firebase

他に用いられているものは何かありますか？

**Comment by YutaUra** [comment]
GraphQL のサーバーとして、 Apollo Server を用いています！
そのほかとしては、 GraphQL-tools なども利用しています。 GraphQL-tools はなくても困らないですが、あると便利系なツールです！

**Comment by nyatinte** [comment]
なるほど！ありがとうございます
ちなみにフロントでGraphQLのSchemeに基づいてHooksを自動生成してくれるのはどのツールですか？

**Comment by YutaUra** [comment]
GraphQL Code Generator（graphql-codegen) です！

**Comment by nyatinte** [comment]
ありがとうございます！個人で色々みてみます！
