### ISSUE TITLE
テスト作成ページのESLintエラー

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#8]
# 概要その1
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/104000239/180439074-37416c72-79c4-4f1e-863a-2379c3e15541.png">

`onSubmit`もきちんと型定義しているのにエラーが起きてしまう

<img width="729" alt="image" src="https://user-images.githubusercontent.com/104000239/180439358-4e12ad18-711c-4f4f-99c4-5c4fbdc54bb1.png">

# 概要その2
<img width="946" alt="image" src="https://user-images.githubusercontent.com/104000239/180439568-d4ddff8a-529c-47e9-9fb7-ea4bc612de50.png">

`testData`は型`testProps`を要素に持つ配列。しかしなぜか`testIndex?: string | undefined`のように`undefined`が追加されてしまう

<img width="757" alt="image" src="https://user-images.githubusercontent.com/104000239/180439647-85ef89cb-d34b-4489-ae64-ab9915df81ab.png">

**Comment by nyatinte** [comment]
1つ目のエラーに関しては解決しました

**Comment by YutaUra** [comment]
2つめの方に関して、 `testData[testNumber]` において、 `testNumber = 999` とかだと `testData[999]` の場合があるからですね。

例えばだけど

```tsx
return (
  <>
    {* ... *}
    {testData[testNumber] && <Test {...testData[testNumber]} /> }
    {* ... *}
  </>
)
```

みたいな感じでやれば解決するだろうか？

**Comment by nyatinte** [comment]
コメントありがとうございます！
存在したらそれを表示っていうふうに条件分岐しないといけないわけですね。参考になりました
コードの修正の方がもありがとうございます

**Comment by nyatinte** [comment]
closeします！
