### ISSUE TITLE
サイドバーを作成

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#84]
### 完了条件
- [ ]  #135 

### この issue が必要な理由
フロントエンド改良のため

### 参考資料

- [figma](https://www.figma.com/file/eT6OhHoi5cwJuIL8ZnUNbY/Engine-%E3%82%AF%E3%83%A9%E3%83%96%E7%94%A8%E3%82%B5%E3%82%A4%E3%83%88-(%E6%94%B9%E8%89%AF%E7%89%88)?node-id=518%3A584)
- [該当ファイル](https://github.com/ycu-engine/ds-club-site/blob/4130b60fb7733bce923e52e99db6fcc635974392/services/frontend/src/components/Header.tsx#L99-L115)
- [Codepen CSS の参考にできそう](https://codepen.io/comehope/pen/mGbpqv)

**Comment by YutaUra** [comment]
@nyatinte がサイドバー部分のコンポーネント分けをおこなってくれるそうです。
コンポーネントわけが終わったらコメントしてください！

**Comment by nyatinte** [comment]
@0514kento @YutaUra 
#105 
コンポーネント分け終わりました！変更をpullしてから作業お願いします

**Comment by nyatinte** [comment]
@0514kento 
作業量的に大変そうなのでタスクもらっちゃいます！
把握よろしくお願いします

**Comment by nyatinte** [comment]
完了
