### ISSUE TITLE
学習記録APIの繋ぎ込み

### ISSUE THREAD

**Issue by takusan2** [ycu-engine/ds-club-site#86]
### 前提条件

- [x] #39
- [x] #38 

### 完了条件

- [x] 学習記録を追加するAPIの繋ぎ込み
「勉強内容」「勉強時間」「記入日」を入力後「追加ボタン」でデータベースに記録される。
- [x] 学習記録を取得するAPIの繋ぎ込み
   -  デフォルトで直近1週間の学習記録の取得
   - 学習記録を指定した期間を取得
   - chartに反映させる

### この issue が必要な理由

学習記録を実際に追加する機能を実現するために必要。
学習記録のAPIを段階的に繋ぎ込むために、追加するAPIと取得するAPIのissueを別々に作成します。

### 参考資料

Figmaへのリンク: [https://www.figma.com/file/MWkK3HSnbCPNLR1ADe3mw9/Engine-%E3%82%AF%E3%83%A9%E3%83%96%E7%94%A8%E3%82%B5%E3%82%A4%E3%83%88?node-id=4%3A28](url)

**Comment by YutaUra** [comment]
以下未対応

- [x] 学習記録順番にソートを行う
- [x] 日付の範囲指定を行う

**Comment by nyatinte** [comment]
# 対応するPR
- #153

**Comment by YutaUra** [comment]
closed by #153
