### ISSUE TITLE
DevExtremeREACTIVE:React Schedulerの環境構築が上手くいかない

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#88]
### 質問の内容

`yarn add`するとエラーを吐いてしまう
詳細は後に記述

### スクリーンショットや該当のコード

この[コンポーネント](https://codesandbox.io/s/reactcalender-xlftno?file=/appoiment.ts)を作成したいと考えています。
[公式ドキュメントのGetting Started](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/)に沿って`yarn add`するが`module not found`となり、不足するライブラリを追加していくうちにエラーを吐いてしまう。

### 参考にした資料など

* 作成したいコンポーネント
https://codesandbox.io/s/reactcalender-xlftno?file=/appoiment.ts
* DevExtremeREACTIVE:React Scheduler -getting started
https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/

**Comment by nyatinte** [comment]
@YutaUra 
解決できず詰まってしまったのでヘルプをお願いしたいです
現在の進捗としては #90 に記載の通り、必要なモジュールを追加し、テスト用のページを作成したところまで進んでいます。

しかしこのようなエラーが起きてしまいます
<img width="960" alt="image" src="https://user-images.githubusercontent.com/104000239/186358721-56e36b9e-5928-4710-a662-8dd63c7f5f2c.png">
1of4とありますが、他も同様のエラーです

**Comment by YutaUra** [comment]
こんな感じで MUI の Provider を設定すれば解消されますが、 UI ライブラリが被ってしまうため、このライブラリは今回選択できない可能性が高いです。
MUI を使わずに、 Chakra UI だけでも利用することが可能であれば、使うことができますが難しいかもしれません

https://github.com/ycu-engine/ds-club-site/compare/feature/78...feature/78-mui?expand=1

**Comment by nyatinte** [comment]
ありがとうございます！
別ライブラリの使用という方針に変更します！
issueはクローズしますね
