### ISSUE TITLE
ログインのやり方についてwikiなどにまとめてもらえるとありがたいです

### ISSUE THREAD

**Issue by mokroke** [ycu-engine/ds-club-site#89]
### 質問の内容

yarn devの後のlocalhost:3000にて、ログインのやり方を忘れてしまいました
また見直せるようにwikiなどにログイン方法をまとめていただけるとありがたいです
@YutaUra  @nyatinte @takuya-okada-01 

### スクリーンショットや該当のコード

以下の画面のログインです
<img width="612" alt="Screen Shot 2022-08-24 at 11 42 27" src="https://user-images.githubusercontent.com/78187015/186307619-bb669978-1c6b-4677-87ec-c16ca1dd45e1.png">

**Comment by nyatinte** [comment]
@mokroke 
作成しておきます！

**Comment by nyatinte** [comment]
@mokroke 
wiki作成しました
[ログイン手順wiki](https://github.com/ycu-engine/ds-club-site/wiki/%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E6%89%8B%E9%A0%86)

確認できたらissue closeしちゃってください！

**Comment by mokroke** [comment]
@nyatinte 
ありがと！！！
入れました！！めちゃくちゃ助かりました！！

**Comment by YutaUra** [comment]
めっちゃ助かる！ありがとう！
